import React, { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import axios from "axios";
import { serverURL } from "../../App";
import { motion } from "framer-motion";

function InterviewSetup() {
  const [formData, setFormData] = useState({
    experience: "",
    description: "",
    expertise: "",
  });
  const [isLoading, setIsLoading] = useState(false);
  const navigate = useNavigate();

  useEffect(() => {
    if (!localStorage.getItem("userInfo")) {
      alert("You must be logged in to create an interview.");
      navigate("/login");
    }
  }, [navigate]);

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData((prevData) => ({
      ...prevData,
      [name]: value,
    }));
  };

  const handleClose = () => {
    navigate("/dashboard"); 
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setIsLoading(true);

    try {
      const userInfo = JSON.parse(localStorage.getItem("userInfo"));
      const config = {
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${userInfo.token}`,
        },
      };

      const { data } = await axios.post(
        `${serverURL}/api/interviews/generate-from-jd`,
        formData,
        config
      );

      if (data.questions && data.questions.length > 0) {
        alert("✅ Interview questions generated successfully!");
        navigate("/interview", { state: { questions: data.questions, jobRole: formData.expertise } });
      } else {
        throw new Error("No questions were generated by the AI.");
      }
    } catch (error) {
      console.error("Error generating interview questions:", error);
      if (error.response?.status === 401) {
        alert("❌ Your session has expired. Please log in again.");
        navigate("/login");
      } else {
        alert("❌ Failed to generate questions. Please try again.");
      }
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="fixed inset-0 bg-black/80 backdrop-blur-sm flex items-center justify-center z-50 p-4">
      <motion.div 
        initial={{ opacity: 0, scale: 0.9 }}
        animate={{ opacity: 1, scale: 1 }}
        transition={{ duration: 0.3 }}
        className="bg-black/80 backdrop-blur-xl border border-white/10 shadow-[0_0_40px_rgba(255,255,255,0.1)] rounded-[2rem] w-full max-w-lg p-8 relative"
      >
        <button
          onClick={handleClose}
          className="absolute top-6 right-6 text-gray-400 hover:text-white transition-colors"
        >
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-6 h-6">
            <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>

        <h2 className="text-3xl font-bold text-white mb-2">
          Create Interview
        </h2>
        <p className="text-gray-400 text-sm mb-8">
          Configure your custom interview settings.
        </p>

        <form onSubmit={handleSubmit} className="space-y-5">
          <div>
            <label htmlFor="experience" className="block text-gray-300 font-medium mb-1 text-sm">
              Job Experience (in years)
            </label>
            <input
              id="experience"
              name="experience"
              type="number"
              placeholder="e.g. 3"
              value={formData.experience}
              onChange={handleChange}
              className="w-full bg-white/5 border border-white/10 rounded-xl px-4 py-3 text-white placeholder:text-gray-600 focus:ring-1 focus:ring-white/50 focus:border-white/50 focus:outline-none transition-all"
              required
            />
          </div>

          <div>
            <label htmlFor="description" className="block text-gray-300 font-medium mb-1 text-sm">
              Job Description
            </label>
            <textarea
              id="description"
              name="description"
              placeholder="Paste the job description here..."
              rows="4"
              value={formData.description}
              onChange={handleChange}
              className="w-full bg-white/5 border border-white/10 rounded-xl px-4 py-3 text-white placeholder:text-gray-600 focus:ring-1 focus:ring-white/50 focus:border-white/50 focus:outline-none transition-all"
              required
            ></textarea>
          </div>

          <div>
            <label htmlFor="expertise" className="block text-gray-300 font-medium mb-1 text-sm">
              Your Key Skills / Expertise
            </label>
            <input
              id="expertise"
              name="expertise"
              type="text"
              placeholder="e.g. React, Node.js, System Design"
              value={formData.expertise}
              onChange={handleChange}
              className="w-full bg-white/5 border border-white/10 rounded-xl px-4 py-3 text-white placeholder:text-gray-600 focus:ring-1 focus:ring-white/50 focus:border-white/50 focus:outline-none transition-all"
              required
            />
          </div>

          <div className="flex justify-end pt-4">
            <button
              type="submit"
              disabled={isLoading}
              className="bg-white text-black font-bold px-8 py-3 rounded-full shadow-[0_0_20px_rgba(255,255,255,0.2)] hover:bg-gray-200 transition-all transform hover:scale-105 active:scale-95 disabled:bg-gray-800 disabled:text-gray-500 disabled:cursor-not-allowed disabled:transform-none disabled:shadow-none"
            >
              {isLoading ? "Generating..." : "Generate & Start"}
            </button>
          </div>
        </form>
      </motion.div>
    </div>
  );
}

export default InterviewSetup;