import React, { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import axios from "axios";
import { serverURL } from "../../App";
import { motion, AnimatePresence } from "framer-motion";
import { FiFileText, FiBriefcase, FiUploadCloud, FiX, FiCheckCircle } from "react-icons/fi";

function InterviewSetup() {
  const [interviewType, setInterviewType] = useState("jd"); // "jd" or "resume"
  const [formData, setFormData] = useState({
    experience: "",
    description: "",
    expertise: "",
  });
  const [file, setFile] = useState(null);
  const [isLoading, setIsLoading] = useState(false);
  const navigate = useNavigate();

  useEffect(() => {
    if (!localStorage.getItem("userInfo")) {
      alert("You must be logged in to create an interview.");
      navigate("/login");
    }
  }, [navigate]);

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData((prevData) => ({
      ...prevData,
      [name]: value,
    }));
  };

  const handleFileChange = (e) => {
    const selectedFile = e.target.files[0];
    if (selectedFile && selectedFile.type === "application/pdf") {
      setFile(selectedFile);
    } else {
      alert("Please upload a PDF file.");
    }
  };

  const handleClose = () => {
    navigate("/dashboard"); 
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setIsLoading(true);

    try {
      const userInfo = JSON.parse(localStorage.getItem("userInfo"));
      const token = userInfo ? userInfo.token : null;

      let response;
      if (interviewType === "resume") {
        if (!file) {
          alert("Please upload your resume.");
          setIsLoading(false);
          return;
        }
        const uploadData = new FormData();
        uploadData.append("resume", file);
        uploadData.append("jobDescription", formData.description);

        response = await axios.post(
          `${serverURL}/api/interviews/generate-from-resume`,
          uploadData,
          {
            headers: {
              "Content-Type": "multipart/form-data",
              Authorization: `Bearer ${token}`,
            },
          }
        );
      } else {
        response = await axios.post(
          `${serverURL}/api/interviews/generate-from-jd`,
          formData,
          {
            headers: {
              "Content-Type": "application/json",
              Authorization: `Bearer ${token}`,
            },
          }
        );
      }

      const data = response.data;

      if (interviewType === "resume") {
        // Resume-based returns { question, topic, difficulty }
        if (data.question) {
          alert("✅ Resume-based interview question generated!");
          navigate("/interview", { 
            state: { 
              questions: [data.question], 
              jobRole: "Resume-Based Interview",
              topic: data.topic,
              difficulty: data.difficulty
            } 
          });
        } else {
          throw new Error("Failed to generate question from resume.");
        }
      } else {
        // JD-based returns { questions: [] }
        if (data.questions && data.questions.length > 0) {
          alert("✅ Interview questions generated successfully!");
          navigate("/interview", { state: { questions: data.questions, jobRole: formData.expertise } });
        } else {
          throw new Error("No questions were generated by the AI.");
        }
      }
    } catch (error) {
      console.error("Error generating interview questions:", error);
      if (error.response?.status === 401) {
        alert("❌ Your session has expired. Please log in again.");
        navigate("/login");
      } else {
        alert("❌ Failed to generate questions. Please try again.");
      }
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="fixed inset-0 bg-black/80 backdrop-blur-sm flex items-center justify-center z-50 p-4">
      <motion.div 
        initial={{ opacity: 0, scale: 0.9 }}
        animate={{ opacity: 1, scale: 1 }}
        transition={{ duration: 0.3 }}
        className="bg-black/80 backdrop-blur-xl border border-white/10 shadow-[0_0_40px_rgba(255,255,255,0.1)] rounded-[2.5rem] w-full max-w-xl p-8 relative overflow-hidden"
      >
        <button
          onClick={handleClose}
          className="absolute top-6 right-6 text-gray-400 hover:text-white transition-colors z-10"
        >
          <FiX size={24} />
        </button>

        <div className="mb-8">
          <h2 className="text-3xl font-bold text-white mb-2">
            Start Your Interview
          </h2>
          <p className="text-gray-400 text-sm">
            Choose your preferred interview mode and get started.
          </p>
        </div>

        {/* Mode Selection Tabs */}
        <div className="flex p-1 bg-white/5 rounded-2xl mb-8 border border-white/5">
          <button
            onClick={() => setInterviewType("jd")}
            className={`flex-1 flex items-center justify-center gap-2 py-3 rounded-xl transition-all ${
              interviewType === "jd" 
                ? "bg-white text-black shadow-lg" 
                : "text-gray-400 hover:text-white hover:bg-white/5"
            }`}
          >
            <FiBriefcase />
            <span className="font-semibold">Job Description</span>
          </button>
          <button
            onClick={() => setInterviewType("resume")}
            className={`flex-1 flex items-center justify-center gap-2 py-3 rounded-xl transition-all ${
              interviewType === "resume" 
                ? "bg-white text-black shadow-lg" 
                : "text-gray-400 hover:text-white hover:bg-white/5"
            }`}
          >
            <FiFileText />
            <span className="font-semibold">Resume-Based</span>
          </button>
        </div>

        <form onSubmit={handleSubmit} className="space-y-6">
          <AnimatePresence mode="wait">
            {interviewType === "jd" ? (
              <motion.div
                key="jd-fields"
                initial={{ opacity: 0, x: -20 }}
                animate={{ opacity: 1, x: 0 }}
                exit={{ opacity: 0, x: 20 }}
                className="space-y-5"
              >
                <div>
                  <label className="block text-gray-300 font-medium mb-2 text-sm">
                    Job Experience (years)
                  </label>
                  <input
                    name="experience"
                    type="number"
                    placeholder="e.g. 3"
                    value={formData.experience}
                    onChange={handleChange}
                    className="w-full bg-white/5 border border-white/10 rounded-2xl px-5 py-3.5 text-white placeholder:text-gray-600 focus:ring-2 focus:ring-white/20 focus:border-white/20 focus:outline-none transition-all"
                    required
                  />
                </div>
                <div>
                  <label className="block text-gray-300 font-medium mb-2 text-sm">
                    Target Expertise
                  </label>
                  <input
                    name="expertise"
                    type="text"
                    placeholder="e.g. React, Node.js, Frontend"
                    value={formData.expertise}
                    onChange={handleChange}
                    className="w-full bg-white/5 border border-white/10 rounded-2xl px-5 py-3.5 text-white placeholder:text-gray-600 focus:ring-2 focus:ring-white/20 focus:border-white/20 focus:outline-none transition-all"
                    required
                  />
                </div>
              </motion.div>
            ) : (
              <motion.div
                key="resume-fields"
                initial={{ opacity: 0, x: 20 }}
                animate={{ opacity: 1, x: 0 }}
                exit={{ opacity: 0, x: -20 }}
                className="space-y-5"
              >
                <div>
                  <label className="block text-gray-300 font-medium mb-2 text-sm">
                    Upload Your Resume (PDF)
                  </label>
                  <div className={`group relative flex h-32 cursor-pointer flex-col items-center justify-center rounded-2xl border-2 border-dashed transition-all ${
                    file ? "border-white/40 bg-white/5" : "border-white/10 hover:border-white/20 hover:bg-white/5"
                  }`}>
                    <input
                      type="file"
                      accept=".pdf"
                      onChange={handleFileChange}
                      className="absolute inset-0 opacity-0 cursor-pointer"
                    />
                    {file ? (
                      <div className="flex items-center gap-3 text-white">
                        <FiCheckCircle className="text-green-400" size={24} />
                        <span className="font-medium truncate max-w-[200px]">{file.name}</span>
                      </div>
                    ) : (
                      <div className="flex flex-col items-center text-gray-400">
                        <FiUploadCloud size={32} className="mb-2 group-hover:text-white transition-colors" />
                        <span className="text-sm">Click to upload resume</span>
                      </div>
                    )}
                  </div>
                </div>
              </motion.div>
            )}
          </AnimatePresence>

          <div>
            <label className="block text-gray-300 font-medium mb-2 text-sm">
              Job Description
            </label>
            <textarea
              name="description"
              placeholder="Paste the job requirements here..."
              rows="4"
              value={formData.description}
              onChange={handleChange}
              className="w-full bg-white/5 border border-white/10 rounded-2xl px-5 py-3.5 text-white placeholder:text-gray-600 focus:ring-2 focus:ring-white/20 focus:border-white/20 focus:outline-none transition-all resize-none"
              required
            ></textarea>
          </div>

          <div className="pt-4">
            <button
              type="submit"
              disabled={isLoading}
              className="w-full bg-white text-black font-bold py-4 rounded-2xl shadow-xl hover:bg-gray-200 transition-all transform hover:scale-[1.02] active:scale-[0.98] disabled:bg-gray-800 disabled:text-gray-500 disabled:cursor-not-allowed flex items-center justify-center gap-3"
            >
              {isLoading ? (
                <>
                  <div className="h-5 w-5 animate-spin rounded-full border-2 border-black/20 border-t-black" />
                  <span>Generating...</span>
                </>
              ) : (
                "Start Interview"
              )}
            </button>
          </div>
        </form>
      </motion.div>
    </div>
  );
}

export default InterviewSetup;